apps/login_registration/urls.py
from django.conf.urls import url
from . import views          
urlpatterns = [
    url(r'^main$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^dashboard$', views.dash, name='dash'),
    url(r'^wish_items/create$', views.create_display, name='create_display'),
    url(r'^wish_items/add_new$', views.add_new_product, name='add_new_product'),
    url(r'^wish_items/(?P<product_id>\d+)$', views.product_display, name='product_display'),
    url(r'^add_to_wish/(?P<id>\d+)$', views.add_to_wish, name='add_to_wish'),
    url(r'^remove_from_wish/(?P<wish_id>\d+)$', views.remove_from_wish, name='remove_from_wish'),
    url(r'^delete/(?P<product_id>\d+)$', views.delete, name='delete')
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^', include('apps.login_registration.urls', namespace='lr'))
]

apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re

# models

class UserManager(models.Manager):
    def validate(self, post_data):
        errors = []
        p = post_data
        name, username, password, cpassword, date_hired = p['name'], p['username'], p['password'], p['cpassword'], p['date_hired']
        
        if not name or not username or not password or not cpassword or not date_hired:
            errors.append("All fields are required")
        else:
            if len(name) < 3 or len(username) < 3:
                errors.append("Invalid names")            
            if len(password) <8:
                errors.append("Invalid password!")
            elif password != cpassword:
                errors.append("Passwords must match")
        
        if not errors:
            if self.filter(username=username):
                errors.append("username already in use")
            else:     
                hash_in = bcrypt.hashpw(password.encode(), bcrypt.gensalt())                
                return self.create(
                    name = name,
                    username = username,
                    password = hash_in,
                    date_hired = date_hired
                )    
        return errors

    def validate_login(self, login_data):
        errors = []
        username, password = login_data['username'], login_data['password']
        if not username or not password:
            errors.append("All fields are required")
        else:
            if len(username) <3 or len(password) <8:
                errors.append("Invalid fields") 
            #  existing username check
            else:
                persons = self.filter(username=username)
                if len(persons) == 0:
                    errors.append("Please register")
                else:
                    hash1 = persons[0].password
                    if bcrypt.checkpw(password.encode(), hash1.encode()) == True:
                        # print ("password match")
                        # taking only the first user from the filtered persons, index=0
                        user = persons[0]
                        return user
                    else:
                        errors.append("Invalid password")
        return errors

class ProductManager(models.Manager):
    def validate_new_product(self, product_data, id):
        errors = []
        product_name = product_data['product_name']
        if not product_name:
            errors.append("Field is required! Cannot be empty!!")
        else:
            if len(product_name) < 4:
                errors.append("Invalid item/product!")
            if not errors:
                if self.filter(product_name=product_name):
                    errors.append("Product already created")
                else:                
                    return self.create(
                        product_name = product_name,
                        user = User.objects.get(id=id)
                    )    
        return errors

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    date_hired = models.DateField()
    objects = UserManager()
    # def __str__(self):
    #     return "<User object: {} {} {}>".format(self.name, self.username, self.password)

class Product(models.Model):
    product_name = models.CharField(max_length=255)
    # one User can create many products
    user = models.ForeignKey(User, related_name="products")
    created_at = models.DateTimeField(auto_now_add = True)
    objects = ProductManager()

class Wish(models.Model):
    # one Product can belong to many user's wishes
    product = models.ForeignKey(Product, related_name="wishes")
    # one User can have many wishes
    user = models.ForeignKey(User, related_name="wishes")
    created_at = models.DateTimeField(auto_now_add = True)

apps/login_registration/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from .models import *
from django.contrib import messages
from django.contrib.messages import error

# render routes
def index(request):
    return render(request,"login_registration/index.html")

def create_display(request):
    return render(request,"login_registration/create_display.html")

def logout(request):
    request.session.clear()
    messages.success(request, 'Successfully logged out!!!')
    return redirect(reverse('lr:index'))

def product_display(request, product_id):
    this_product = Product.objects.get(id=product_id)
    product_data = {
        'product': this_product,
        'wishes': this_product.wishes.all()
    }
    return render(request,"login_registration/product_display.html", product_data)

# logic routes
def register(request):
    if request.method == "POST":        
        result = User.objects.validate(request.POST)
        if type(result) == User:
        # we can also do if type(result) == list, but we consider the best ones first
            request.session['user_id'] = result.id
            messages.success(request, 'Successfully registered!!!')
            return redirect(reverse('lr:dash'))
        else:
            for err in result:
                messages.error(request, err)            
    return redirect(reverse('lr:index'))

def login(request):
    if request.method == "POST":
        result = User.objects.validate_login(request.POST)
        if type(result) == User:            
            request.session['user_id'] = result.id
            messages.success(request, 'Successfully logged in!!!')
            return redirect(reverse('lr:dash'))
        else:
            for err in result:
                messages.error(request, err)       
    return redirect(reverse('lr:index'))
        
def dash(request):
    try:
        me = User.objects.get(id=request.session['user_id'])
        wishes = User.objects.get(id=request.session['user_id']).wishes.all()
        excluded_products_id=[wish.product.id for wish in wishes]

        context = {
            'user': User.objects.get(id=request.session['user_id']),
            'wishes': wishes,
            'products': Product.objects.all().exclude(id__in=excluded_products_id)
        }
        return render(request,"login_registration/dash.html", context)
    except:
        return redirect(reverse('lr:index'))

def add_new_product(request):
    if request.method == "POST":
        id=request.session['user_id']
        result = Product.objects.validate_new_product(request.POST, id)
        if type(result) == Product:   
            me = User.objects.get(id=request.session['user_id'])
            Wish.objects.create(product=result, user=me)         
            messages.success(request, 'Successfully added the product-',result.product_name)
            return redirect(reverse('lr:dash'))
        else:
            for err in result:
                messages.error(request, err)  
    return redirect(reverse('lr:create_display'))

def add_to_wish(request, id):
    this_product = Product.objects.get(id=id)
    me = User.objects.get(id=request.session['user_id'])
    Wish.objects.create(product=this_product, user=me)
    return redirect(reverse('lr:dash'))

def remove_from_wish(request, wish_id):
    this_wish = Wish.objects.get(id=wish_id)
    this_wish.delete()
    return redirect(reverse('lr:dash'))

def delete(request, product_id):
    this_product = Product.objects.get(id=product_id)
    this_product.delete()
    return redirect(reverse('lr:dash'))

apps/login_registration/templates/login_registration/create_display.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'login_registration/css/main.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <a href="{% url 'lr:dash' %}">Home</a> |
        <a href="{% url 'lr:logout' %}">Logout</a><br>
        <h2>Create a New Wishlist Item!</h2><br>
        {% if messages %}
        <ul class="red">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </ul>
        {% endif %}
        
        <form action="{% url 'lr:add_new_product' %}" method='post'>
            {% csrf_token %}
            Item/Product:
            <input type="text" name="product_name" value=""><br>
            <input type="submit" value="Add">
        </form>
    </body>
</html>

apps/login_registration/templates/login_registration/dash.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'login_registration/css/main.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h2>Hello, {{user.name}}!</h2>
        {% if messages %}
        <ul class="green">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </ul>
        {% endif %}
        <a href="{% url 'lr:logout' %}">Logout</a><br>
        <h3>Your wishlist: </h3>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Added by</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for wish in wishes %}
                <tr>
                    <td><a href="{% url 'lr:product_display' wish.product.id %}">{{ wish.product.product_name }}</a></td>
                    <td>{{ wish.product.user.name }}</td>
                    <td>{{ wish.created_at }}</td>
                    <td>
                        {% if request.session.user_id == wish.product.user.id %}
                            <a href="{% url 'lr:delete' wish.product.id %}">delete</a>
                        {% else %}
                            <a href="{% url 'lr:remove_from_wish' wish.id %}">remove from my list</a>
                        {% endif %}   
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <h3>Other user's wishlist:</h3>
        <table>
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Added by</th>
                    <th>Date Added</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td><a href="{% url 'lr:product_display' product.id %}">{{ product.product_name }}</a></td>
                    <td>{{ product.user.name }}</td>
                    <td>{{ product.created_at }}</td>
                    <td>
                        <a href="{% url 'lr:add_to_wish' product.id %}">Add to my wishlist</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'lr:create_display' %}">Add new</a>
    </body>
</html>

apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'login_registration/css/main.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h1>Welcome!</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="red">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <h2>Registration</h2>
        <form action="{% url 'lr:register' %}" method='post'>
            {% csrf_token %}
            Name:
            <br>
            <input type="text" name="name" value="">
            <br> User Name:
            <br>
            <input type="text" name="username" value="">
            <br> Password:
            <br>
            <input type="password" name="password" value="">
            <br> Confirm Password:
            <br>
            <input type="password" name="cpassword" value="">
            <br>
            Date hired:
            <input type="date" name="date_hired" value="">
            <br>
            <input type="submit" value="Register">
        </form>
        <h2>Login</h2>
        
        <form action="{% url 'lr:login' %}" method='post'>
            {% csrf_token %}
            Username:
            <br>
            <input type="text" name="username" value="">
            <br> Password:
            <br>
            <input type="password" name="password" value="">
            <br>
            <br>
            <input type="submit" value="Login">
        </form>
        
    </body>
</html>

apps/login_registration/templates/login_registration/product_display.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'login_registration/css/main.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <a href="{% url 'lr:dash' %}">Home</a> |
        <a href="{% url 'lr:logout' %}">Logout</a><br>
        <h2>{{product.product_name}}</h2>
        <p>Users who added this product/item under their wishlist:</p>
        {% for wish in wishes %}
            <p>{{wish.user.name}}</p>
        {% endfor %}
    </body>
</html>

apps/login_registration/templates/login_registration/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        {% load static %}
        <!-- The line above tells Django to be ready to listen for static files -->
        <link rel="stylesheet" href="{% static 'login_registration/css/main.css' %}" media="screen" title="no title" charset="utf-8">
        <!-- Put the static files in the static folder inside your app.  Django collects files within all static folders and puts them within a single folder -->
    </head>

    <body>
        <h2>Dash! Welcome, {{user.firstname}}</h2>
        {% if messages %}
        <ul class="green">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </ul>
        {% endif %}
        <a href="{% url 'lr:logout' %}"><button>Logout</button></a>
    </body>
</html>